name: Send Data to URL

on:
  push:
    paths:
      - '**/*.py'  # Trigger on changes to Python files only

jobs:
  send_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send data to URL with fixed name and id
        run: |
          # Set fixed values for name and id
          name="AliHassani-ErfanNourbakhsh"  # Example name, replace with your own
          id="01231033907008-01231033907029"  # Example ID, replace with your own

          # Send data using curl
          curl -X POST "https://shams.sython.ir/test.php" \
            -d "name=$name" \
            -d "id=$id"
